### ISSUE TITLE
Extract into a method

### ISSUE THREAD

**Issue by yawboakye** [orignMaster/Java#5]
[L45-49](https://github.com/orignMaster/JavaApps/blob/master/FigureInWords.java#L45-L49), [L52-56](https://github.com/orignMaster/JavaApps/blob/master/FigureInWords.java#L52-L56), and [L59-62](https://github.com/orignMaster/JavaApps/blob/master/FigureInWords.java#L59-62) can be extracted into a method. They repeat enough times to merit a method extraction.

Also, I think converting from an integer to a string, doing substring operations, and back to an integer is a hack. Replace with mathematics.

**Comment by orignMaster** [comment]
I would turn them to functions, but it would have to return two values, ie. num and word, I don't know how i would return two values without necessarily making them global or hackishly putting them in some sort of primitive array type
